## Ch02. Two-State Economy

### Time

In [2]:
1 + 3

4

In [3]:
3 * 4

12

In [4]:
t = 0

In [5]:
t

0

In [6]:
t = 1

In [7]:
type(t)

int

### Money

In [8]:
1 + 0.5

1.5

In [9]:
10.5 - 2

8.5

In [10]:
c = 2 + 0.75

In [11]:
c

2.75

In [12]:
type(c)

float

### Cash Flow

In [13]:
c0 = -9.5

In [14]:
c1 = 11.75

In [15]:
c = (c0, c1)

In [16]:
c

(-9.5, 11.75)

In [17]:
type(c)

tuple

In [18]:
c[0]

-9.5

In [19]:
c[1]

11.75

In [20]:
c = [c0, c1]

In [21]:
c

[-9.5, 11.75]

In [22]:
type(c)

list

In [23]:
c[0]

-9.5

In [24]:
c[1]

11.75

In [25]:
c[0] = 10

In [26]:
c

[10, 11.75]

### Return

In [27]:
c = (-10, 12)

In [28]:
R = sum(c)

In [29]:
R

2

In [30]:
r = R / abs(c[0])

In [31]:
r

0.2

### Present Value

In [32]:
i = 0.1

In [33]:
def D(c1):
    return c1 / (1 + i)

In [34]:
D(12.1)

10.999999999999998

In [41]:
i = 0.01

In [42]:
D(100)

99.00990099009901

### Net Present Value (순현재가치)

In [43]:
def NPV(c):
    return c[0] + D(c[1])

In [44]:
cA = (-10.5, 12.1)

In [45]:
cB = (-10.5, 11)

In [47]:
i = 0.1

In [48]:
NPV(cA)

0.4999999999999982

In [49]:
NPV(cB)

-0.5

### Uncertainty

In [50]:
import numpy as np

In [51]:
c0 = -10 # the cash flow of a project in one year

In [52]:
c1 = np.array((20, 5)) c1 # the relevant cash flows per state of the economy

In [53]:
type(c1)

numpy.ndarray

In [54]:
c1

array([20,  5])

In [55]:
c = (c0, c1)

In [56]:
c

(-10, array([20,  5]))

In [57]:
1.5 * c1 + 2 # a certain operation, scalar multiplication and addition

array([32. ,  9.5])

In [58]:
c1 + 1.5 * np.array((10, 4)) # another operation, a linear combination

array([35., 11.])

### Financial Assets

In [59]:
S0 = 10 # The price today of S0

In [60]:
S1 = np.array((12.5, 7.5)) # The uncertain price in one year as a vector

In [61]:
S = (S0, S1) # The price process as a tuple object

In [62]:
S

(10, array([12.5,  7.5]))

In [63]:
S[0] # Accesses the price of today

10

In [64]:
S[1][0] # Accesses the price in one year in the u(first) state

12.5

In [65]:
S[1][1] # Accesses the price in one year in the d(second) state

7.5

### Probability 

In [66]:
p = 0.4

In [67]:
1 - p

0.6

In [68]:
P = np.array((p, 1-p))

In [69]:
P

array([0.4, 0.6])

### Expectations

In [70]:
P

array([0.4, 0.6])

In [71]:
S0 = 10

In [72]:
S1 = np.array((20, 5))

In [73]:
np.dot(P, S1) # two vectors calculating the expectation value

11.0

### Expected Return

In [74]:
def ER(x0, x1):
    # the expected return: the expection of the price in one year minus the price today
    return np.dot(P, x1) - x0

In [75]:
ER(S0, S1)

1.0

In [78]:
def mu(x0, x1): 
    # The expected rate of return: the expected return divided by the price today
    return (np.dot(P, x1) - x0) / x0

In [77]:
mu(S0, S1)

0.1

### Volatility

In [79]:
def r(x0, x1):
    return (x1 - x0) / x0

In [80]:
r(S0, S1)

array([ 1. , -0.5])

In [81]:
mu = np.dot(P, r(S0, S1))

In [82]:
mu

0.10000000000000003

In [84]:
def sigma2(P, r, mu):
    return np.dot(P, (r - mu) ** 2)

In [85]:
sigma2(P, r(S0, S1), mu)

0.54

In [86]:
def sigma(P, r, mu):
    return np.sqrt(np.dot(P, (r - mu) ** 2))

In [87]:
sigma(P, r(S0, S1), mu)

0.7348469228349535